// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// 🔒 SECURITY: Environment variables are REQUIRED
// NEVER hardcode credentials in source code
// Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in .env.local
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Validate required environment variables
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    '🔒 SECURITY ERROR: Missing Supabase environment variables.\n' +
    'Please set VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY in your .env file.\n' +
    'See .env.example for reference.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // 🔒 SECURITY: Use sessionStorage instead of localStorage for better security
    // sessionStorage is cleared when browser closes, reducing XSS token theft risk
    storage: typeof window !== 'undefined' ? window.sessionStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
    // 🔒 SECURITY: Detect session from URL hash (for email confirmation links)
    detectSessionInUrl: true,
    // 🔒 SECURITY: Flow type for PKCE (more secure than implicit flow)
    flowType: 'pkce',
  }
});